@startuml Display UML


interface TextBasedDisplay {
    # char line_break
    + void show_text(string v)
}

TextBasedDisplay <|-- LCDDisplay

TextBasedDisplay <|-- OLedDisplay

TextBasedDisplay <|-- ConsoleDisplay

@enduml
