@startuml Weather UML


struct WeatherInfo {
    + float temperature
    + float humidity
}

interface WeatherGetter {
    + void get_weather(struct WeatherInfo *weather)
}

DHT11WeatherGetter <|-- WeatherGetter

@enduml

