@startuml Weather UML


struct WeatherInfo {
    + float temperature
    + float humidity
}

interface WeatherStatusTask {
    + [[noreturn]] void run(struct WeatherInfo *weather)
}

WeatherStatusTask <|-- DHT11WeatherTask
WeatherStatusTask <|-- RandomValuesWeatherTask

@enduml

